### ISSUE TITLE
Error: redirect_uri_mismatch after authorizing the app

### ISSUE THREAD

**Issue by ghinda** [koliada/FireTasks#1]
After authorizing the app in the OAuth popup, it redirects to a `400 Error: redirect_uri_mismatch` page from Google, with the mention `The redirect URI in the request: https://koliada.github.io/FireTasks/app.html did not match a registered redirect URI.`.

![oauth-error](https://cloud.githubusercontent.com/assets/325171/5221757/ceb409f4-768b-11e4-87c6-c6180fdfc201.png)

You can only see the error on the desktop. The FxOS app is stuck in an infinite loading state.

It seems that something happened to the redirect url sometime in the last couple of days, since I was successfully using it on FxOS previously.

**Comment by koliada** [comment]
Wow, seems that Tasks API was **TURNED OFF** for several days after my experiments last weekend!
So bad.
Try now please.

Thank you!

**Comment by ghinda** [comment]
Yeah, same thing right now. Maybe it takes a while for the API to turn back on?

**Comment by koliada** [comment]
I noticed that on your screenshot it's `https` protocol.
I have never seen GitHub Pages using `https` before.
Anyway, I've registered this URL, try now please.

Thanks!

**Comment by ghinda** [comment]
It's working now, both on desktop and on my Flame. Thanks a lot!

**Comment by koliada** [comment]
Thank you!
PS: I'm working on new revamped architecture for full offline work support and speed improvements, so stay in touch :)

**Comment by ghinda** [comment]
That's cool! Just out of curiosity, are you using any "mvc" library?

**Comment by koliada** [comment]
No. I started this project to dive into JS and although I've gained some experience during last year, I still want to keep this as pure as possible. This is my training ground :)

**Comment by ghinda** [comment]
Sounds great! Looking forward to it!
